# Generated by Django 5.0.7 on 2024-08-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB_EVENT', '0003_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='user', max_length=30),
        ),
    ]
