# Generated by Django 5.0.7 on 2024-07-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('role', models.CharField()),
                ('password', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('role', models.CharField()),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
