# Generated by Django 5.0.7 on 2024-07-30 12:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('login', models.CharField(max_length=30, unique=True)),
                ('role', models.CharField(default='user')),
                ('password', models.CharField(max_length=30)),
                ('secret_phrase', models.CharField(max_length=30)),
                ('avatar', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('email',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('city', models.CharField(default='', max_length=50)),
                ('description', models.CharField(max_length=1024)),
                ('price', models.IntegerField(default=0)),
                ('image', models.CharField(max_length=100)),
                ('age_limit', models.IntegerField(default=0)),
                ('start_time', models.TimeField(null=True)),
                ('duration', models.IntegerField(default=0)),
                ('user_limit', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('event_name',),
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WEB_EVENT.user')),
            ],
            options={
                'ordering': ('email',),
            },
            bases=('WEB_EVENT.user',),
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WEB_EVENT.user')),
            ],
            options={
                'ordering': ('email',),
            },
            bases=('WEB_EVENT.user',),
        ),
    ]
