# Generated by Django 5.0.7 on 2024-07-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB_EVENT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1024)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
