# Generated by Django 5.0.7 on 2024-08-08 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEB_EVENT', '0003_alter_event_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('pk',)},
        ),
    ]
